#+TITLE: Type-safe printf() with the C preprocessor
#+AUTHOR: pecan
#+DATE: 2026-03-13
#+BLOG_TAGS: c

It always annoyed me slightly that even though the intended types of arguments to ~printf()~ are known at compile time
the format string still has to be runtime interpreted. Also, if you use fixed-width integer types extensively it gets
annoying to write ~PRIu64~, ~PRIi32~, etc everywhere. Fortunately with modern C features and some slight (ab)use of the
C preprocessor we can do much better.

Let's write a compile-time, type-safe ~printf()~ replacement. For fun, let's do it without libc and use only facilities
provided by the operating system.

Our strategy is use the preprocessor to rewrite the following

#+BEGIN_SRC c :tangle iobuf.c :noweb strip-export :exports none
  #include <nolibc/nolibc.h>
  #define assert(x) do{ if (!(x)) __builtin_debugtrap(); }while(0)
  #define MIN(a,b) ({ __auto_type $a = (a); __auto_type $b = (b); $a < $b ? $a : $b; })
  #define MAX(a,b) ({ __auto_type $a = (a); __auto_type $b = (b); $a > $b ? $a : $b; })

  <<pp0>>
  <<pp1>>
  <<pp2>>

  <<iobuf_def>>

  <<io_primitives>>

  <<writeint>>

  <<writeptr>>

  <<stringfmt>>
  <<writestring>>

  <<dispatch>>
  
  <<putline>>


  int main(int argc, const char *argv[argc])
  {
      <<defstdout>>
      int a = argv[1][0] - '0', b = argv[2][0] - '0';
      <<example>>
      PutLine(&stdout, a < b ? "ab" : "much longer string");
      return 0;
  }
#+END_SRC

#+NAME: example
#+BEGIN_SRC c
  const char *world = "world";
  int x = 283;
  PutLine(&stdout, "hello ", world, " x: ", x);
#+END_SRC

into something like

#+BEGIN_SRC c
  WriteCString(&stdout, "hello ");
  WriteCString(&stdout, world);
  WriteCString(&stdout, " x: ");
  WriteInt(&stdout, x);
  WriteCString(&stdout, "\n");
#+END_SRC

First, let's take care of the actual I/O primitives. We'll define a structure for buffering output:

#+NAME: iobuf_def
#+BEGIN_SRC c
  enum ioerror { IOERR_OK = 0, IOERR_WRITE_FAILED = -1 };
  struct iobuf {
      ssize_t cap;
      ssize_t len;
      uint8_t *buf __attribute__((counted_by(cap)));
      int fd;
      enum ioerror err;
  };
#+END_SRC

We need a file descriptor to write to, a buffer to accumulate our formatted output in, and a flag to check for errors. I
[[https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1428r0.pdf][prefer signed sizes]] and use the [[https://gcc.gnu.org/onlinedocs/gcc/Common-Attributes.html#index-counted_005fby][~counted_by~]] attribute to enable catching errors with ~-fsanitize=bounds~, and for
documentation purposes.

#+BEGIN_EXPORT html
<details class="status-field-border"><summary>Aside: Portability</summary>
#+END_EXPORT
For the sake of simplicity we're sticking to just Linux here, but it doesn't require much more code to support other
systems. All that has to be done is hide the ~fd~ member behind a typedef that expands to ~int~ on POSIX and ~HANDLE~ on
Win32, and then introduce a wrapper function to perform the write via the appropriate OS interface (~write()~ on POSIX
or ~WriteFile()~ on Win32).

Unfortunately, on most platforms besides Linux and Windows we do have to link to libc, since Linux is unusual in having
a stable syscall interface. Other *nix operating systems do not have stable syscall numbers and require you to go
through libc. Windows is similar in requiring you to go through the interface exposed in kernel32.dll rather than making
raw syscalls, but kernel32.dll is mapped into every process's address space automatically, so you don't have to link
against anything extra.
#+BEGIN_EXPORT html
</details>
#+END_EXPORT

How do we get one of these ~struct iobuf~ instances? Well, somewhere in our ~main()~ function we can put

#+NAME: defstdout
#+BEGIN_SRC c
  uint8_t buf[256];
  struct iobuf stdout = {.cap = sizeof(buf), .buf = buf, .fd = 1};
#+END_SRC

and then pass that to anything that needs to write to stdout.

Now we need a couple of functions to append to our buffer and flush our output to the OS:

#+NAME: io_primitives
#+BEGIN_SRC c
  void Flush(struct iobuf *io)
  {
      const uint8_t *buf = io->buf;
      // partial writes are possible on Linux, where write() succeeds but writes fewer bytes than requested.
      while (io->len > 0) {
          ssize_t written = sys_write(io->fd, buf, io->len);
          if (written < 0) {
              io->err = IOERR_WRITE_FAILED;
              break;
          }
          buf += written;
          io->len -= written;
      }
  }

  void WriteBytes(struct iobuf *io, ssize_t n, const uint8_t bytes[n])
  {
      ssize_t written = 0;
      while (io->err == 0 && written < n) {
          ssize_t free = io->cap - io->len;
          ssize_t z = MIN(free, n);
          __builtin_memcpy(io->buf + io->len, bytes, z);
          written += z;
          io->len += z;
          bytes += z;
          if (z < n) Flush(io);
      }
  }
#+END_SRC

All the ~WriteBytes()~ function does is copy to our internal buffer and then flush it to the OS once it fills ups.
~Flush()~ is responsible for doing the actual OS write, here done by calling the [[https://github.com/torvalds/linux/blob/1f318b96cc84d7c2ab792fcc0bfd42a7ca890681/tools/include/nolibc/sys.h#L886-L888][~sys_write()~]] function provided by the
[[https://lwn.net/Articles/920158/][nolibc.h header]] that ships with recent Linux kernels. One complication is that the ~write()~ syscall can succeed but
write fewer bytes than requested, so we have to call it in a loop until it either fails or writes everything. On Win32,
writes either succeed fully or not at all, so one need not worry about partial writes and the ~Flush()~ function is much
simpler.

The advantage of keeping our error code inside the ~struct iobuf~ instead of returning it from ~Flush()~ is that we can
call ~WriteBytes()~ many times and then check the error only once at the end. Note that if an error happens
~WriteBytes()~ becomes a no-op, so we effectively fall through to wherever the error is handled.

With our output primitives out of the way we can get to the formatting parts. We need to define a bunch of functions
that format the things we care about and call ~WriteBytes()~ to store their results in our output buffer.

#+NAME: writeint
#+BEGIN_SRC c
  void WriteInt(struct iobuf *io, int64_t x)
  {
      // longest possible int64 decimal representation is 20 characters (-9223372036854775808)
      uint8_t s[20];
      ssize_t i = 20;
      bool neg = x < 0;
      if (neg) x = -x;
      do s[--i] = '0' + x % 10; while (x /= 10);
      if (neg) s[--i] = '-';
      WriteBytes(io, 20 - i, s + i);
  }

  void WriteUInt(struct iobuf *io, uint64_t x)
  {
      // also 20: no sign character but maximum uint64 is one character longer (18446744073709551615)
      uint8_t s[20];
      ssize_t i = 20;
      do s[--i] = '0' + x % 10; while (x /= 10);
      WriteBytes(io, 20 - i, s + i);
  }
#+END_SRC

Integers are very straightforward. We only need two functions, one for signed and one for unsigned, since we can cast
any smaller integer to a ~(u)int64_t~ without the output changing. Floats are much more challenging, since correctly
converting floats to strings that can be parsed back to exactly the same value is a surprisingly complex problem. The
most practical option is to existing high-quality float-to-string implementation like [[https://github.com/ulfjack/ryu][ryu]] or [[https://github.com/vitaut/zmij][zmij]].

Pointers are pretty much the same as integers:

#+NAME: writeptr
#+BEGIN_SRC c
  void WritePtr(struct iobuf *io, void *p)
  {
      uintptr_t x = (uintptr_t)p;
      uint8_t s[16];
      ssize_t i = 16;
      do s[--i] = (x % 16 < 10 ? '0' + x % 16 : 'a' + x % 16 - 10); while (x /= 16);
      WriteBytes(io, 16 - i, s + i);
  }
#+END_SRC

For strings I like to avoid traditional C-style ~\0~-terminated strings, but we want the convenience of being able to
write string literals without explicitly passing their length. Fortunately this is possible with a bit of trickery and a
clang extension.

We'll start by defining a struct to hold pointer + length pairs. Later you'll see why we wrap these into a struct rather
than passing separate arguments.

#+NAME: stringfmt
#+BEGIN_SRC c
  struct stringfmt { ssize_t len; uint8_t *ptr __attribute__((counted_by(len))); };

  #define $S(n,s) ((struct stringfmt){.len = (n), .ptr = (s)})
#+END_SRC

We define a helper macro to construct ~struct stringfmt~​s for readability, and ~$S~ is visually a bit evocative of the
traditional printf-style ~%s~ format specifier. One nice advantage of using structs for wrapping our format options is
that designated initializers can be used a bit like keyword arguments, which is much more readable than normal printf
specifiers. One can imagine defining a struct for advanced integer formatting options like

#+BEGIN_SRC c
  struct intfmt {
      int64_t x;
      int32_t width;
      enum { JUSTIFY_RIGHT, JUSTIFY_LEFT } justify;
      bool hex;
      bool force_sign;
      uint8_t pad;
  };

  #define $I(i,...) ((struct intfmt){.x = (i) __VA_OPT__(,) __VA_ARGS__})
#+END_SRC

which would allow things like ~PutLine("x: ", $I(x, .width = 10, .force_sign = true, .pad = '0'))~. I find this easier
than remembering the order of fields in ~printf("x: %+010" PRIi64 "\n")~, and it avoids special cases like the printf
~*~ specifier for variable widths. While there's something to be said for compactness, I use the more complex format
specifiers rarely enough that I always forget the exact syntax for them.

Returning to strings, we need two functions: one that takes our pointer + length pairs and one that takes a standard
~const char *~ string.

#+NAME: writestring
#+BEGIN_SRC c
  void WriteStringFmt(struct iobuf *io, struct stringfmt fmt)
  {
      WriteBytes(io, fmt.len, fmt.ptr);
  }

  void WriteCString(struct iobuf *io, const char *const s __attribute__((pass_dynamic_object_size(2))))
  {
      ssize_t len = __builtin_dynamic_object_size(s, 2);
      assert(len > 0);  // fails if we were passed something other than a string literal
      WriteBytes(io, len - 1 /* trim off \0 */, (const uint8_t *)s);
  }
#+END_SRC

The trick is that this uses the clang-specific [[https://clang.llvm.org/docs/AttributeReference.html#pass-object-size-pass-dynamic-object-size][~pass_dynamic_object_size~]] attribute to cause the caller to pass an
extra, invisible parameter containing the size of the ~s~ argument if it is statically known. This parameter is then
retrieved with the [[https://clang.llvm.org/docs/LanguageExtensions.html#evaluating-object-size][~__builtin_dynamic_object_size()~]] function. If the size of ~s~ can't be determined by the compiler
~__builtin_dynamic_object_size()~ returns 0, so we can tell if we were called with a string whose size was not a
compile-time constant, which usually means anything that's not a string literal. This is an error on the part of the
caller and fails the assert.

(Alternatively, you could just call ~strlen()~, but we're trying to avoid libc and zero-terminated strings as much as
possible.)

The ~_dynamic~ part means the compiler is allowed to insert a small amount of code to more accurately deduce the size of
the object. For example, in a case like the following:

#+BEGIN_SRC c
  WriteCString(io, a < b ? "ab" : "much longer string");
#+END_SRC

If we had used ~__attribute__((pass_object_size(2)))~ then we would always receive a ~len~ of 3, since that is all the
compiler is able to prove is always accessible. With ~pass_dynamic_object_size~, this gets rewritten to something like
~WriteCString(io, a < b ? "…" : "…", a < b ? 3 : 19)~ instead.

That aside, writing strings just involves shuffling bytes to our output buffer. You can imagine implementing other
extensions like minimum width and padding fairly straightforwardly.

With our individual formatting functions out of the way it's time to tie it all together into a nicer API. You could use
them as they are and manually make a separate function call for each variable you want to print but we would like to
write that part automatically, as in the example at the beginning of the article.

The first step is to use C11's ~_Generic~ feature to dispatch to one of our formatting functions based on the type of
the argument. This is pretty much just manual function overloading.

#+NAME: dispatch
#+BEGIN_SRC c
  void Fail(void);

  #define DISPATCH_WRITE(x) \
      _Generic((x), \
          int8_t: WriteInt, \
          uint8_t: WriteUInt, \
          int16_t: WriteInt, \
          uint16_t: WriteUInt, \
          int32_t: WriteInt, \
          uint32_t: WriteUInt, \
          int64_t: WriteInt, \
          uint64_t: WriteUInt, \
          size_t: WriteUInt, \
          ssize_t: WriteInt, \
          /* if you were to implement floats: \
             float: WriteFloat, \
             double: WriteDouble, */ \
          char *: WriteCString, \
          const char *: WriteCString, \
          struct stringfmt: WriteStringFmt, \
          default: _Generic((x) - (x), ptrdiff_t: WritePtr, default: Fail) \
      )($_io, (x));
#+END_SRC

~_Generic~ works by taking an expression and a list of ~type: replacement~ pairs. It doesn't evaluate the controlling
expression but matches its type against the pairs and replaces itself with the matching replacement expression. I tend
to think of it as somewhere between the preprocessor and the compiler. Unlike the preprocessor it can access types, but
it's completely eliminated by the time code generation starts. Its main use is for type-generic math so you can write
~sqrt(2.0f)~ instead of sqrtf.

The nested ~_Generic~ on ~(x) - (x)~ is to allow dispatching any pointer (other than the ones explicitly listed above
that) to ~WritePtr()~. Though any (non-function) C pointer is implicitly convertible to ~void *~, ~void *~ in ~_Generic~
only matches actual void pointers. However, the result of subtracting any type of pointer from itself is always a
~ptrdiff_t~, so we can match on that instead rather than requiring the caller to explicitly cast pointers to ~void *~.

One quirk of ~_Generic~ is that each replacement expression has to typecheck independently before the ~_Generic~ is
eliminated. This is why you usually have to write ~_Generic(x, char *: f_str, float: f_float)(x)~ instead of
~_Generic(x, char *: f_str(x), float: f_float(x))~. This is also what the ~default: Fail~ branch in the nested generic
is for, since that branch has to type check even if another branch is already matched by the outer ~_Generic~. We don't
need to define the ~Fail()~ function anywhere, since we explicitly want a compile error if we ever emit it (which would
mean we tried to print something without a formatter).

It's also worth noting that ~_Generic~ considers ~const~ and non-~const~ pointers to be different types, and one will
never match the other.

You may notice the reference to the ~$_io~ variable which is not yet defined. We'll get back to that.

Now we need some way to call our ~DISPATCH_WRITE()~ macro for each argument to ~PutLine()~. Fortunately, looping with
the C preprocessor got a lot easier with the ~__VA_OPT__()~ feature in C23.

~__VA_OPT__()~ is legal in the expansion of a variadic macro and expands to its argument if ~__VA_ARGS__~ is of non-zero
length, and expands to nothing otherwise. The intended use case is when you have a macro like

#+BEGIN_SRC c
  #define WARN(msg,...) printf("[WARNING] " msg, __VA_ARGS__)
#+END_SRC

If ~WARN()~ is called with only the first argument it will expand to ~printf("[WARNING] <message>",)~, which is a syntax
error. With ~__VA_OPT__()~ you can write it as

#+BEGIN_SRC c
  #define WARN(msg,...) printf("[WARNING] " msg __VA_OPT__(,) __VA_ARGS__)
#+END_SRC

and it will properly include the comma only when necessary.

Previously this could be accomplished with non-standard features like the special behavior of the ~, ## __VA_ARGS__~
sequence in gcc, but ~__VA_OPT__()~ is both standardized and more flexible. For instance, you can include other macros
in the argument of ~__VA_OPT__()~, which will expand if ~__VA_OPT__()~ expands.

You might be able to see how we're going to abuse this to loop over our arguments to ~PutLine()~. ~__VA_OPT__()~ seems a
lot like the base case of recursion: we can use it to execute another macro if we still have arguments left, and stop
iteration otherwise.

The techniques in this section are mainly from [[https://github.com/pfultz2/Cloak/wiki/C-Preprocessor-tricks,-tips,-and-idioms][these]] [[https://www.scs.stanford.edu/~dm/blog/va-opt.html][two]] excellent articles.

When a macro is expanded its expansion is scanned again for macros; however by default preprocessor macros cannot expand
recursively. That is, ~#define f(x) f((x)+1)~ when called as ~f(1)~ expands to ~f(1+1)~ and not ~1+1+1+…~. When a macro
is expanded the token corresponding to its name is marked (referred to as "painted blue") and blue tokens are ignored as
expansion candidates during re-scan. This includes during any expansions triggered during the re-scan, so this can't be
bypassed by e.g.

#+BEGIN_SRC c
  #define f(x) f_recurse((x)+1)
  #define f_recurse(x) f(x)
#+END_SRC

To get around this we need an extra layer of indirection to prevent the token from being painted blue.

#+NAME: pp0
#+BEGIN_SRC c
  #define EMPTY()
  #define DEFER(x) x EMPTY()
#+END_SRC

If we pass a macro to ~DEFER()~ we can prevent it from being painted blue, but then we need a way to force a re-scan.

#+BEGIN_SRC c
  #define EXPAND(...) __VA_ARGS__

  #define f(x) DEFER(f_recurse) () ((x)+1)
  #define f_recurse() f
  
  EXPAND(DEFER(f)(1))
#+END_SRC
#+CAPTION: [[https://godbolt.org/z/6qYKKo6hW][Example]]

One expansion is easy, but with only one layer of ~EXPAND()~ it stops there. Fortunately it's not hard to have an exponential number of expansions.

#+NAME: pp1
#+BEGIN_SRC c
  #define EVAL(...)  EVAL1(EVAL1(EVAL1(__VA_ARGS__)))
  #define EVAL1(...) EVAL2(EVAL2(EVAL2(__VA_ARGS__)))
  #define EVAL2(...) EVAL3(EVAL3(EVAL3(__VA_ARGS__)))
  #define EVAL3(...) EVAL4(EVAL4(EVAL4(__VA_ARGS__)))
  #define EVAL4(...) EVAL5(EVAL5(EVAL5(__VA_ARGS__)))
  #define EVAL5(...) __VA_ARGS__
#+END_SRC

We can get [[https://godbolt.org/z/ddx48Y787][365]][fn:: Each level ~EVALn~ gets called 3^n times, plus one for the outermost ~EVAL()~, plus the first
expansion for free.] expansions out of 6 lines. This does put a hard limit on the number of arguments to ~PutLine()~ we
can support, but it's trivial to add more if necessary.

With this, we can build a loop in the C preprocessor:

#+NAME: pp2
#+BEGIN_SRC c
  #define FOREACH(f,...) __VA_OPT__(EVAL(FOREACH_IMPL(f, __VA_ARGS__)))
  #define FOREACH_IMPL(f,x,...) f(x) __VA_OPT__(DEFER(FOREACH_RECURSE) () (f, __VA_ARGS__))
  #define FOREACH_RECURSE() FOREACH_IMPL
#+END_SRC

This is admittedly a bit arcane, but now that it's built it's pretty easy to use.

Finally we can glue it all together:

#+NAME: putline
#+BEGIN_SRC c
  #define PutLine(io,...) do{ struct iobuf *$_io = (io); FOREACH(DISPATCH_WRITE, __VA_ARGS__, "\n"); Flush($_io); }while(0)
#+END_SRC

In case evaluating ~(io)~ has side effects we evaluate it once here and stash the results in ~$_io~, which is used in
~DISPATCH_WRITE()~.

It should be pretty clear how this works now. We loop through all the arguments of ~PutLine()~ (except the iobuf) using
our preprocessor metaprogramming and for each of them use ~_Generic~ to dispatch to the correct formatting function for
an argument of that type. Those convert their arguments to strings and append to a buffer, which we flush with the
appropriate OS function.

Overall, this isn't a lot of code for an arguably nicer API than ~printf()~. glibc ~printf()~ alone is [[https://sourceware.org/git/?p=glibc.git;a=blob;f=stdio-common/vfprintf-internal.c;h=14ac0d97625297fc25989e741b98f15cd9c1b6ed;hb=HEAD][over 1500 lines
of code]][fn:: This doesn't even include float-to-string, which is another 1200+ (though it would bloat ours quite a lot
as well).] and needs special compiler support to issue warnings. musl is [[https://git.musl-libc.org/cgit/musl/tree/src/stdio/vfprintf.c][much better]], but still on the order of ~450
LOC. While our implementation is very barebones, it's easy to extend and can provide options via standard C features
like designated initializers rather than the limited printf mini-language. Also, it's easy to add support for your own
custom types by implementing a ~Write*~ function for them and adding it to the ~_Generic~ list.[fn:: I was hoping it
might be possible to add new ~_Generic~ cases without editing the macro directly by abusing the gcc
~_Pragma("push_macro")~ and ~_Pragma("pop_macro")~ extensions from inside a helper macro with an API like
~DEFINE_FORMATTER(type, WriteType)~, but this is extremely brittle and I can't get it to work in the general case.]

Should you use this in production? Probably not, given that most people are not quite as fond of grotesque preprocessor
macros as I am. It's more just meant to exhibit some modern C features and present a novel use for them. I will say that
I do use an implementation very much like this in some of my personal projects where no one else has to see it and I
find it very usable and convenient.

[[./iobuf.c][Collected code in this article]] (requires a recent version of clang)
